### ISSUE TITLE
Xorg not starting in GKE with  no screens found error

### ISSUE THREAD

**Issue by krishnaraj1** [EmbarkStudios/gke-accelerated-xorg-example#4]
I am trying to run Xorg server that use GPU inside Google Kubernetes Engine

I followed this guide (https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#ubuntu) to setup a GKE cluster with Nvidia Testla T4 GPU. The nodes are with Ubuntu (Docker). 
I deployed gke-xorg-example to this cluster.

My deployment.yml :

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-xorg-example
  labels:
    app: gke-xorg-example
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: gke-xorg-example
  template:
    metadata:
      labels:
        app: gke-xorg-example
    spec:
      containers:
        - name: xorg
          image: "embarkstudios/xorg:latest"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
              nvidia.com/gpu: "1"
          env:
            - name: LD_LIBRARY_PATH
              value: "/usr/local/nvidia/lib64"
          args: [ "/bin/sleep", "infinity" ]
        - name: glxgears
          image: "embarkstudios/glxgears:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DISPLAY
              value: ":0"
```

These are the logs of the xorg container : 

```
+ export XINITRC=/etc/X11/xinitrc
+ XINITRC=/etc/X11/xinitrc
+ COMMAND='/bin/sleep infinity'
+ [[ -z /bin/sleep infinity ]]
+ cat
+ chmod +x /etc/X11/xinitrc
+ exec /usr/bin/env XINITRC=/etc/X11/xinitrc /usr/bin/xinit /etc/X11/xinitrc -- /usr/bin/Xorg -verbose 3 -novtswitch -keeptty -verbose -allowMouseOpenFail


X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-138-generic x86_64 Ubuntu
Current Operating System: Linux gke-xorg-example-77996b5dc8-bkbl2 5.4.0-1039-gke #41~18.04.1-Ubuntu SMP Sat Mar 20 14:57:07 UTC 2021 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-1039-gke root=PARTUUID=e0001179-e649-415c-890d-562fb24bb2eb ro console=ttyS0 net.ifnames=0
Build Date: 25 October 2018  04:11:27PM
xorg-server 2:1.19.6-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Thu May 27 04:30:52 2021
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(==) ServerLayout "Layout0"
(**) |-->Screen "Screen0" (0)
(**) |   |-->Monitor "Monitor0"
(**) |   |-->Device "Device0"
(**) Option "DontZap" "false"
(==) Automatically adding devices
(==) Automatically enabling devices
(==) Automatically adding GPU devices
(==) Automatically binding GPU devices
(==) Max clients allowed: 256, resource mask: 0x1fffff
(WW) The directory "/usr/share/fonts/X11/misc" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
        Entry deleted from font path.
(WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
        Entry deleted from font path.
(==) FontPath set to:
        built-ins
(**) ModulePath set to "/usr/local/nvidia/lib64/xorg/modules/drivers,/usr/local/nvidia/lib64/xorg/modules/extensions,/usr/lib/xorg/modules"
(II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
(II) Loader magic: 0x56194639a020
(II) Module ABI versions:
        X.Org ANSI C Emulation: 0.4
        X.Org Video Driver: 23.0
        X.Org XInput driver : 24.1
        X.Org Server Extension : 10.0
(EE) dbus-core: error connecting to system bus: org.freedesktop.DBus.Error.FileNotFound (Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory)
(--) using VT number 5

(II) xfree86: Adding drm device (/dev/dri/card0)
(--) PCI: (0:0:4:0) 10de:1eb8:10de:12a2 rev 161, Mem @ 0xc0000000/16777216, 0x7c0000000/268435456, 0x7d0000000/33554432
(II) no primary bus or device found
        falling back to /sys/devices/pci0000:00/0000:00:04.0/drm/card0
(II) LoadModule: "glx"
(II) Loading /usr/lib/xorg/modules/extensions/libglx.so
(II) Module glx: vendor="X.Org Foundation"
        compiled for 1.19.6, module version = 1.0.0
        ABI class: X.Org Server Extension, version 10.0
(II) LoadModule: "nvidia"
(WW) Warning, couldn't open module nvidia
(II) UnloadModule: "nvidia"
(II) Unloading nvidia
(EE) Failed to load module "nvidia" (module does not exist, 0)
(==) Matched nouveau as autoconfigured driver 0
(==) Matched nouveau as autoconfigured driver 1
(==) Matched modesetting as autoconfigured driver 2
(==) Matched fbdev as autoconfigured driver 3
(==) Matched vesa as autoconfigured driver 4
(==) Assigned the driver to the xf86ConfigLayout
(II) LoadModule: "nouveau"
(WW) Warning, couldn't open module nouveau
(II) UnloadModule: "nouveau"
(II) Unloading nouveau
(EE) Failed to load module "nouveau" (module does not exist, 0)
(II) LoadModule: "modesetting"
(II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
(II) Module modesetting: vendor="X.Org Foundation"
        compiled for 1.19.6, module version = 1.19.6
        Module class: X.Org Video Driver
        ABI class: X.Org Video Driver, version 23.0
(II) LoadModule: "fbdev"
(WW) Warning, couldn't open module fbdev
(II) UnloadModule: "fbdev"
(II) Unloading fbdev
(EE) Failed to load module "fbdev" (module does not exist, 0)
(II) LoadModule: "vesa"
(WW) Warning, couldn't open module vesa
(II) UnloadModule: "vesa"
(II) Unloading vesa
(EE) Failed to load module "vesa" (module does not exist, 0)
(II) modesetting: Driver for Modesetting Kernel Drivers: kms
(WW) Falling back to old probe method for modesetting
(EE) Screen 0 deleted because of no matching config section.
(II) UnloadModule: "modesetting"
(EE) Device(s) detected, but none match those in the config file.
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Cannot assign requested address
/usr/bin/xinit: server error
```

Is there anything else that need to be done in the cluster to make it work? 
I tried installing  cuda package to the container,  but same error.
